[pytest]
log_cli = true
log_cli_level = ERROR
log_level = ERROR
timeout = 200
testpaths = code/default/lib/tests code/default/x_tunnel/tests
norecursedirs = python3 *.egg __pycache__ .git
addopts = --ignore=code/default/lib/tests/test_xtunnel_socks5.py --ignore=code/default/lib/tests/test_github_access.py --ignore=code/default/x_tunnel/tests/test_proxy.py --ignore=code/default/x_tunnel/tests/test_stability.py
