name: lint_python
on:
  pull_request:
  push:
    branches: [master, test]
jobs:
  testing_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pytest pytest-timeout
      - run: pip install -r requirements.txt || true

      - shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          pytest -v code/default/lib/tests --timeout=60 || true

      - name: Integrate testing
        shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          python code/default/launcher/tests/integrate_testing.py || true

  testing_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pytest pytest-timeout
      - run: pip install -r requirements.txt || true

      - shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          pytest -v code/default/lib/tests --timeout=60 || true

      - name: Integrate testing
        shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          python code/default/launcher/tests/integrate_testing.py || true

  testing_mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pytest pytest-timeout
      - run: pip install -r requirements.txt || true

      - shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          pytest -v code/default/lib/tests --timeout=60 || true

      - name: Integrate testing
        shell: bash
        env:
          PYTHONPATH: ./code/default:./code/default/lib/noarch
        run: |
          python code/default/launcher/tests/integrate_testing.py || true